import type {
  AssistantDestination,
  GuestPersona,
  PendingLogin,
  ShopRole,
  StaffKind,
} from "@/lib/assistant/types";

const OWNER: ShopRole[] = ["owner"];
const OPS: ShopRole[] = ["owner", "manager"];
const TILL: ShopRole[] = ["owner", "manager", "cashier"];
const POS: ShopRole[] = ["owner", "manager", "cashier", "warehouse"];
const STOCK: ShopRole[] = ["owner", "manager", "warehouse"];
const SALES: ShopRole[] = ["owner", "manager", "cashier", "accountant"];
const AUDIT: ShopRole[] = ["owner", "accountant", "support_admin", "super_admin"];
const STOREFRONT: ShopRole[] = ["owner", "manager", "super_admin"];

export const PERSONA_CHIPS = [
  { id: "owner", label: "Shop Owner", payload: "::role:owner" },
  { id: "manager", label: "Manager", payload: "::role:manager" },
  { id: "staff", label: "Staff", payload: "::role:staff" },
  { id: "admin", label: "Admin", payload: "::role:admin" },
  { id: "super_admin", label: "Super admin", payload: "::role:super_admin" },
] as const;

export const STAFF_KIND_CHIPS = [
  { id: "cashier", label: "Cashier", payload: "::staff:cashier" },
  { id: "warehouse", label: "Warehouse", payload: "::staff:warehouse" },
  { id: "accountant", label: "Accountant", payload: "::staff:accountant" },
  { id: "delivery", label: "Delivery", payload: "::staff:delivery" },
] as const;

export const GUEST_STARTER_CHIPS = [
  { id: "account", label: "Access my account", payload: "I want to access my account" },
  { id: "demo", label: "Guest demo", payload: "::demo" },
  { id: "pos", label: "Take a payment", payload: "How do I take a payment?" },
  { id: "stock", label: "Check stock", payload: "Where do I see stock?" },
] as const;

export function loginForPersona(persona: GuestPersona | StaffKind): PendingLogin {
  const map: Record<GuestPersona | StaffKind, PendingLogin> = {
    owner: { persona: "owner", roleLabel: "Shop Owner", next: "/dashboard" },
    manager: { persona: "manager", roleLabel: "Manager", next: "/dashboard" },
    staff: { persona: "staff", roleLabel: "Staff", next: "/dashboard" },
    admin: { persona: "admin", roleLabel: "Admin", next: "/platform" },
    super_admin: { persona: "super_admin", roleLabel: "Super admin", next: "/platform" },
    cashier: { persona: "cashier", roleLabel: "Cashier", next: "/pos" },
    warehouse: { persona: "warehouse", roleLabel: "Warehouse", next: "/products" },
    accountant: { persona: "accountant", roleLabel: "Accountant", next: "/sales" },
    delivery: { persona: "delivery", roleLabel: "Delivery", next: "/online-orders" },
  };
  return map[persona];
}

export const DESTINATIONS: AssistantDestination[] = [
  {
    id: "home",
    title: "Home",
    href: "/",
    demoHref: "/demo",
    public: true,
    keywords: ["home", "landing", "start page", "welcome", "হোম", "baile", "início"],
    answer: "This is the ShopOS home page — sign in, create a shop, or ask me to open any feature.",
    guestAnswer:
      "You are on the ShopOS home page. I can start a guest demo, or open sign-in once you tell me your role.",
  },
  {
    id: "login",
    title: "Sign in",
    href: "/login",
    demoHref: "/login",
    public: true,
    keywords: [
      "sign in",
      "signin",
      "log in",
      "login page",
      "password",
      "লগ ইন",
      "লগইন",
      "logáil isteach",
      "entrar",
    ],
    answer: "The sign-in page is ready. Use the email and password for your ShopOS account.",
    guestAnswer: "Tell me your role and I will open email and password here in the chat.",
  },
  {
    id: "signup",
    title: "Create account",
    href: "/signup",
    demoHref: "/signup",
    public: true,
    keywords: [
      "sign up",
      "signup",
      "create account",
      "register",
      "new shop",
      "trial",
      "pilot",
      "অ্যাকাউন্ট",
      "cuntas",
      "criar conta",
    ],
    answer: "Create a ShopOS account and start a 30-day pilot. No card is required to begin.",
    guestAnswer: "I can take you to create an account, or start a guest demo first.",
  },
  {
    id: "forgot",
    title: "Forgot password",
    href: "/forgot-password",
    demoHref: "/forgot-password",
    public: true,
    keywords: ["forgot password", "reset password", "recover password"],
    answer: "Use Forgot password to receive a reset email.",
    guestAnswer: "I can open the password reset page for you.",
  },
  {
    id: "dashboard",
    title: "Dashboard",
    href: "/dashboard",
    demoHref: "/demo#dashboard",
    keywords: [
      "dashboard",
      "overview",
      "kpis",
      "today's take",
      "reports",
      "profit",
      "how is the shop doing",
      "হোম",
      "início",
    ],
    lookupTopic: "sales",
    answer:
      "The dashboard shows today's take, profit, low stock, open tills, and outstanding supplier orders.",
    guestAnswer:
      "The owner dashboard is the shop's daily scoreboard — sales, stock alerts, and tills in one place.",
  },
  {
    id: "pos",
    title: "Point of sale",
    href: "/pos",
    demoHref: "/demo#pos",
    roles: POS,
    lookupTopic: "tills",
    keywords: [
      "pos",
      "point of sale",
      "till sale",
      "take a payment",
      "take payment",
      "charge a customer",
      "barcode",
      "wireless scanner",
      "barcode scanner",
      "scanner",
      "receipt",
      "cash drawer",
      "customer display",
      "customer screen",
      "change",
      "card confirm",
      "card machine",
      "কাউন্টার",
      "tillir",
      "caixa",
      "পেমেন্ট",
    ],
    answer:
      "POS is where you scan items and take payment. USB or wireless barcode scanners work as a keyboard — pair one scanner to each till computer. Cash and Card are large buttons — no dropdowns. Cash: the drawer opens, tap the note they gave you, and you see the change. Card: take it on your own machine, then Confirm to record a card sale. Customer screen opens a display of items, prices, and the total.",
    guestAnswer:
      "The till is a tablet POS: scan, take cash or card, print a receipt, and stock updates at once.",
    forbiddenHint: "POS is for owners, managers, cashiers, and warehouse staff.",
  },
  {
    id: "sales",
    title: "Sales",
    href: "/sales",
    demoHref: "/demo#sales",
    roles: SALES,
    lookupTopic: "sales",
    keywords: [
      "sales history",
      "receipts",
      "refund",
      "completed sales",
      "what did we sell",
      "takings",
    ],
    answer: "Sales lists every completed till and online sale, with receipts and payment methods.",
    guestAnswer:
      "Sales is the history of every basket — useful for owners, managers, cashiers, and accountants.",
    forbiddenHint: "Sales history is for owners, managers, cashiers, and accountants.",
  },
  {
    id: "online-orders",
    title: "Online orders",
    href: "/online-orders",
    demoHref: "/demo#online",
    roles: ["owner", "manager", "delivery"],
    lookupTopic: "online",
    keywords: [
      "online orders",
      "website orders",
      "click and collect",
      "delivery orders",
      "customer order",
    ],
    answer: "Online orders from your public shop share the same stock as the till.",
    guestAnswer: "Online orders land here when a customer checks out on your public shop.",
    forbiddenHint: "Online orders are for owners, managers, and delivery.",
  },
  {
    id: "sessions",
    title: "Till sessions",
    href: "/sessions",
    demoHref: "/demo#till",
    roles: TILL,
    lookupTopic: "tills",
    keywords: [
      "till",
      "tills",
      "session",
      "z report",
      "z-report",
      "cash up",
      "close till",
      "cash variance",
    ],
    answer:
      "Till sessions open and close the cash drawer for Morning, Evening, or Night. Each till (up to 10 per branch) is counted on its own. Final shift accounting rolls all tills together.",
    guestAnswer:
      "Each shift starts by opening a till and ends by counting cash against the Z-report.",
    forbiddenHint: "Till sessions are for owners, managers, and cashiers.",
  },
  {
    id: "open-till",
    title: "Open a till",
    href: "/sessions/open",
    demoHref: "/demo#till",
    roles: TILL,
    lookupTopic: "tills",
    keywords: [
      "open till",
      "open a till",
      "start shift",
      "opening cash",
      "float",
      "morning",
      "evening",
      "night",
    ],
    answer:
      "Open a till with Morning, Evening, or Night, and the opening float, before taking sales.",
    guestAnswer: "A cashier opens the till with the float, then POS becomes available.",
    forbiddenHint: "Only owners, managers, and cashiers can open a till.",
  },
  {
    id: "products",
    title: "Products",
    href: "/products",
    demoHref: "/demo#stock",
    roles: STOCK,
    lookupTopic: "stock",
    keywords: [
      "products",
      "catalogue",
      "catalog",
      "sku",
      "barcode list",
      "items",
      "inventory list",
      "stock",
      "low stock",
      "on hand",
      "স্টক",
      "stoc",
    ],
    answer: "Products is the catalogue: prices, VAT, barcodes, and on-hand stock per branch.",
    guestAnswer: "The product list is where you add SKUs, prices, VAT codes, and photos.",
    forbiddenHint: "The catalogue is for owners, managers, and warehouse staff.",
  },
  {
    id: "new-product",
    title: "Add a product",
    href: "/products/new",
    demoHref: "/demo#stock",
    roles: STOCK,
    keywords: ["add product", "new product", "create product", "new sku", "add item"],
    answer: "Use Add product to create a SKU with price, VAT, barcode, and branch stock.",
    guestAnswer:
      "New products are added from the catalogue, then they appear on POS and the online shop.",
    forbiddenHint: "Adding products is for owners, managers, and warehouse staff.",
  },
  {
    id: "scan-in",
    title: "Scan in",
    href: "/stock/receive",
    demoHref: "/demo#stock",
    roles: STOCK,
    lookupTopic: "stock",
    keywords: [
      "scan in",
      "receive stock",
      "barcode receive",
      "stock scanner",
      "delivery scan",
      "add stock scan",
      "wireless scanner",
      "warehouse scan",
      "goods in scan",
    ],
    answer:
      "Scan in is for deliveries: scan the barcode, ShopOS names the product, you enter the quantity, and on-hand stock updates. Pair a USB or wireless scanner to that computer. Use Deliveries if you have a supplier invoice.",
    guestAnswer:
      "Warehouse staff scan barcodes to book stock in. The till uses a different scanner for selling.",
    forbiddenHint: "Scan in is for owners, managers, and warehouse staff.",
  },
  {
    id: "import",
    title: "Bulk import",
    href: "/products/import",
    demoHref: "/demo#stock",
    roles: STOCK,
    keywords: ["import", "csv", "bulk import", "upload products"],
    answer: "Bulk import loads many products from a CSV in one go.",
    guestAnswer: "A CSV import is the fastest way to load a full catalogue.",
    forbiddenHint: "Imports are for owners, managers, and warehouse staff.",
  },
  {
    id: "categories",
    title: "Categories",
    href: "/categories",
    demoHref: "/demo#stock",
    roles: STOCK,
    keywords: ["categories", "category", "aisle", "department"],
    answer: "Categories group products on POS and the online shop.",
    guestAnswer: "Categories keep the till and the online shop easy to browse.",
    forbiddenHint: "Categories are for owners, managers, and warehouse staff.",
  },
  {
    id: "brands",
    title: "Brands",
    href: "/brands",
    demoHref: "/demo#stock",
    roles: STOCK,
    keywords: ["brands", "brand", "supplier brand"],
    answer: "Brands sit on each product and help filter the catalogue.",
    guestAnswer: "Brands are a simple filter on products — Tayto, Coca-Cola, and so on.",
    forbiddenHint: "Brands are for owners, managers, and warehouse staff.",
  },
  {
    id: "suppliers",
    title: "Suppliers",
    href: "/suppliers",
    demoHref: "/demo#purchasing",
    roles: STOCK,
    keywords: ["suppliers", "wholesaler", "vendor", "who do we buy from"],
    answer: "Suppliers are the wholesalers you buy from. Each one can have purchase orders.",
    guestAnswer: "Supplier records feed purchase orders and goods receipts.",
    forbiddenHint: "Suppliers are for owners, managers, and warehouse staff.",
  },
  {
    id: "new-supplier",
    title: "Add a supplier",
    href: "/suppliers/new",
    demoHref: "/demo#purchasing",
    roles: STOCK,
    keywords: ["add supplier", "new supplier", "create supplier"],
    answer: "Add a supplier with name, account code, and contact details.",
    guestAnswer: "New suppliers are added before you raise a purchase order.",
    forbiddenHint: "Adding suppliers is for owners, managers, and warehouse staff.",
  },
  {
    id: "purchase-orders",
    title: "Purchase orders",
    href: "/purchase-orders",
    demoHref: "/demo#purchasing",
    roles: STOCK,
    lookupTopic: "purchasing",
    keywords: ["purchase orders", "purchase order", "supplier order", "po list", "outstanding po"],
    answer:
      "Purchase orders are what you send to suppliers. Receiving stock happens on goods receipts.",
    guestAnswer:
      "A purchase order is the shop's order to a wholesaler. Stock is not added until you receive it.",
    forbiddenHint: "Purchase orders are for owners, managers, and warehouse staff.",
  },
  {
    id: "new-po",
    title: "New purchase order",
    href: "/purchase-orders/new",
    demoHref: "/demo#purchasing",
    roles: STOCK,
    lookupTopic: "purchasing",
    keywords: [
      "new purchase order",
      "create po",
      "raise a po",
      "order stock",
      "order from supplier",
    ],
    answer: "Raise a new purchase order, then receive it when the delivery arrives.",
    guestAnswer: "Raise a PO when you need to restock from a supplier.",
    forbiddenHint: "Creating purchase orders is for owners, managers, and warehouse staff.",
  },
  {
    id: "goods-receipts",
    title: "Receiving",
    href: "/goods-receipts",
    demoHref: "/demo#purchasing",
    roles: STOCK,
    lookupTopic: "purchasing",
    keywords: ["goods receipts", "receiving", "delivery in", "stock in", "grn"],
    answer: "Goods receipts book supplier deliveries into stock against a purchase order.",
    guestAnswer: "When a delivery arrives, receiving is how stock actually lands on the shelf.",
    forbiddenHint: "Receiving is for owners, managers, and warehouse staff.",
  },
  {
    id: "new-grn",
    title: "New goods receipt",
    href: "/goods-receipts/new",
    demoHref: "/demo#purchasing",
    roles: STOCK,
    keywords: ["new goods receipt", "receive stock", "book in delivery", "record delivery"],
    answer: "Start a goods receipt to book a supplier delivery into a branch.",
    guestAnswer: "Receiving a delivery updates on-hand stock immediately once you finalise it.",
    forbiddenHint: "Booking in deliveries is for owners, managers, and warehouse staff.",
  },
  {
    id: "audit",
    title: "Audit log",
    href: "/audit",
    demoHref: "/demo#audit",
    roles: AUDIT,
    keywords: ["audit", "audit log", "who changed", "history of changes"],
    answer: "The audit log is the legal trail of who changed stock, sales, and settings.",
    guestAnswer: "Every important change is written to the audit log for owners and accountants.",
    forbiddenHint: "The audit log is for owners, accountants, and platform admins.",
  },
  {
    id: "shops",
    title: "My shops",
    href: "/settings/shops",
    demoHref: "/demo#settings",
    roles: OWNER,
    keywords: ["my shops", "switch shop", "another shop", "multi shop"],
    answer: "My shops lists every shop on your billing account. Open one to work in it.",
    guestAnswer: "Owners can run more than one shop on the same ShopOS account.",
    forbiddenHint: "Shop switching is for owners.",
  },
  {
    id: "branches",
    title: "Branches",
    href: "/settings/branches",
    demoHref: "/demo#settings",
    roles: OPS,
    keywords: ["branches", "branch", "locations", "second shop", "multi branch"],
    answer: "Branches are the physical locations under this shop. Stock and tills are per branch.",
    guestAnswer: "A shop can have several branches — each with its own till and stock.",
    forbiddenHint: "Branches are for owners and managers.",
  },
  {
    id: "billing",
    title: "Billing",
    href: "/settings/billing",
    demoHref: "/demo#billing",
    roles: OWNER,
    lookupTopic: "billing",
    keywords: [
      "billing",
      "subscription",
      "plan",
      "invoice",
      "monthly fee",
      "card on file",
      "shopos payment",
      "pay shopos",
      "upgrade",
      "বিল",
      "billeáil",
      "faturação",
    ],
    answer:
      "Billing is where the owner manages the ShopOS plan, card on file, and subscription status.",
    guestAnswer:
      "ShopOS billing is the owner's subscription — plan, card, trial, and invoices. It is separate from taking a customer payment on the till.",
    forbiddenHint: "Billing is only available to the shop owner.",
  },
  {
    id: "subscribe",
    title: "Add a card",
    href: "/onboarding/subscribe",
    demoHref: "/demo#billing",
    roles: OWNER,
    lookupTopic: "billing",
    keywords: ["add a card", "add card", "needs card", "trial card", "unlock pos"],
    answer: "Add a card to finish onboarding. POS stays locked until a card is on file.",
    guestAnswer: "After the free trial setup, the owner adds a card so the till can go live.",
    forbiddenHint: "Only the shop owner can add a billing card.",
  },
  {
    id: "team",
    title: "Team",
    href: "/settings/team",
    demoHref: "/demo#team",
    roles: OPS,
    lookupTopic: "team",
    keywords: ["team", "staff", "invite", "invite staff", "users", "roles", "cashier account"],
    answer: "Team is where owners and managers invite staff and set their role.",
    guestAnswer: "Invite cashiers, warehouse, accountants, and managers from Team settings.",
    forbiddenHint: "Team invites are for owners and managers.",
  },
  {
    id: "tills",
    title: "Tills",
    href: "/settings/tills",
    demoHref: "/demo#settings",
    roles: OPS,
    keywords: [
      "tills",
      "till license",
      "devices",
      "revoke till",
      "desktop app license",
      "offline license",
    ],
    answer:
      "Tills lists every computer that has activated ShopOS. The owner can revoke a till so it cannot keep selling. Downloading the desktop app is not a license.",
    guestAnswer:
      "Each till must check in with ShopOS. Unpaid or revoked tills cannot take sales, including after a short offline window.",
    forbiddenHint: "Till devices are for owners and managers.",
  },
  {
    id: "storefront",
    title: "Online shop settings",
    href: "/settings/storefront",
    demoHref: "/demo#online",
    roles: STOREFRONT,
    keywords: [
      "storefront",
      "online shop settings",
      "shop settings",
      "logo",
      "opening hours",
      "website template",
      "shop design",
      "theme",
    ],
    answer:
      "Online shop settings let you pick one of ten website templates, plus name, logo, pickup, and delivery. The chosen design is what customers see when the shop is published.",
    guestAnswer: "The public shop is configured here, then customers order at /shop/your-slug.",
    forbiddenHint: "Storefront settings are for owners and managers.",
  },
  {
    id: "onboarding",
    title: "Set up your shop",
    href: "/onboarding",
    demoHref: "/demo",
    keywords: ["onboarding", "set up shop", "create shop", "wizard"],
    answer: "Onboarding creates your first shop, branch, and till.",
    guestAnswer: "New owners run a short wizard to name the shop, add a branch, and start a trial.",
  },
  {
    id: "platform",
    title: "Platform home",
    href: "/platform",
    demoHref: "/demo#platform",
    platformOnly: true,
    keywords: ["platform", "control centre", "control center", "all shops admin"],
    answer: "Platform home is the ShopOS control centre for every customer shop.",
    guestAnswer: "Super admins see every shop, trials, and shops that need payment.",
    forbiddenHint: "Platform admin is for ShopOS super admins and support admins.",
  },
  {
    id: "platform-tenants",
    title: "All shops",
    href: "/platform/tenants",
    demoHref: "/demo#platform",
    platformOnly: true,
    lookupTopic: "billing",
    keywords: [
      "all shops",
      "find a shop",
      "record payment",
      "extend trial",
      "pause shop",
      "suspend",
    ],
    answer:
      "All shops lists every tenant. From a shop you can record payment, extend a trial, or pause access.",
    guestAnswer: "Platform staff look up a customer shop here to help with billing or access.",
    forbiddenHint: "All shops is for ShopOS platform staff.",
  },
  {
    id: "platform-staff",
    title: "Admin access",
    href: "/platform/staff",
    demoHref: "/demo#platform",
    platformOnly: true,
    keywords: ["platform staff", "admin access", "grant admin", "support admin"],
    answer: "Admin access grants ShopOS staff permission to manage customer shops.",
    guestAnswer: "Only super admins grant other platform admins access.",
    forbiddenHint: "Admin access is for ShopOS platform staff.",
  },
];

export const DEMO_STEPS: Array<{
  id: string;
  title: string;
  body: string;
  href: string;
}> = [
  {
    id: "welcome",
    title: "Guest demo",
    body: "A short look at each area. Sign in when you want a real shop.",
    href: "/demo",
  },
  {
    id: "pos",
    title: "Point of sale",
    body: "Scan. Take cash or card. Print a receipt. Needs an open till.",
    href: "/demo#pos",
  },
  {
    id: "stock",
    title: "Stock & catalogue",
    body: "Products, prices, and what is on the shelf. Scan in books a delivery by barcode.",
    href: "/demo#stock",
  },
  {
    id: "purchasing",
    title: "Suppliers & receiving",
    body: "Raise a purchase order, then book the delivery on Receiving. Only then does on-hand stock increase.",
    href: "/demo#purchasing",
  },
  {
    id: "online",
    title: "Online shop",
    body: "The public shop uses the same catalogue and stock as the till. Click & collect and delivery orders appear under Online orders.",
    href: "/demo#online",
  },
  {
    id: "billing",
    title: "Billing",
    body: "Only the shop owner manages the ShopOS subscription. Taking money from a customer happens on POS — that is a different payment.",
    href: "/demo#billing",
  },
  {
    id: "team",
    title: "Team & roles",
    body: "Owner, manager, cashier, warehouse, accountant, and delivery each see only the screens they need.",
    href: "/demo#team",
  },
  {
    id: "platform",
    title: "Platform super admin",
    body: "ShopOS staff can see every customer shop, record a payment, extend a trial, or pause a shop that has not paid.",
    href: "/demo#platform",
  },
];

export function getDestination(id: string): AssistantDestination | undefined {
  return DESTINATIONS.find((d) => d.id === id);
}

export function withGuide(href: string, guide: string): string {
  if (href.includes("#") && href.startsWith("/demo")) return href;
  const hashIndex = href.indexOf("#");
  const hash = hashIndex >= 0 ? href.slice(hashIndex) : "";
  const base = hashIndex >= 0 ? href.slice(0, hashIndex) : href;
  const sep = base.includes("?") ? "&" : "?";
  return `${base}${sep}guide=${encodeURIComponent(guide)}${hash}`;
}
